name: 'Run App Hintz, Samantha'

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: restore nuget
        run: nuget restore GithubActions.sln
      - name: build
        run: msbuild GithubActions.sln /p:Configuration=Release
      - name: run unit tests
        run: |
          $testDll = Get-ChildItem -Recurse -Filter "Tests.dll" | Select-Object -First 1
          dotnet test $testDll.SamanthaHintz